# -*- coding: utf-8 -*-
"""Teste_OnOff2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YbO0BiogPt9ytOxj8GHVr1AWkJkrJM53

# Simulação simplificada

$dv/dt = fac(t,Y) - gef + far(t,Y)$

$dz/dt = v$

onde

$fac(t,Y) = amp(t,Y)*esp(t,Y)$
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

def dYdt( t, Y, \
         amp = lambda t, Y, **kwrd: 1.3, \
         far = lambda t, Y, **kwrd: -.05*Y[0], \
         esp = lambda t, Y, **kwrd: -np.sin(2*np.pi*Y[1]), \
         gef = 1, calculaEq = False, **kwrd ):
  if calculaEq:
    fun2solve = lambda z:dYdt( t=t, Y=[0,z], amp=amp, esp=esp, far=far, gef=gef, **kwrd )[0]
    zEq = fsolve( fun2solve, Y[1] )[0]
    return zEq
  v, z = Y
  dvdt = amp(t,Y,**kwrd)*esp(t,Y,**kwrd) - gef + far(t,Y,**kwrd)
  dzdt = v
  return [dvdt, dzdt]

def resolve( funR=dYdt, t_span = [0., 40.], y0='Eq', dt = 0.1, \
              events=None, rtol=1e-6, atol=1e-9, max_step=np.inf, \
            SHOW=True, RETORNA=False, **kwrd ):
  if (y0=='Eq'):
    z0 = funR( t=-1, Y=[0, 0], calculaEq=True, **kwrd )
    v0 = 0.
    y0Ef = [v0, z0]
  else:
    y0Ef = y0.copy()

  # print( f'{y0Ef = }' )
  t_eval=np.arange(t_span[0], t_span[-1]+dt, dt)
  t_eval = t_eval[t_eval<=t_span[-1]]
  SOL = solve_ivp( fun=lambda t, Y: funR(t,Y,**kwrd), t_span=t_span, \
                   y0=y0Ef, method='DOP853', t_eval=t_eval, \
                   max_step=max_step, rtol=rtol, atol=atol, events=events )

  if SHOW:
    plt.figure()
    plt.subplot(2,1,1)
    plt.plot( SOL.t, SOL.y[0], '.-' )
    plt.ylabel( 'v' )
    plt.subplot(2,1,2)
    plt.plot( SOL.t, SOL.y[1], '.-' )
    plt.ylabel( 'z' )
    plt.xlabel( 't' )
    plt.show()
  if RETORNA:
    return SOL

def fazOff(t, Y, dtOff=.05, tIni=0, ampOn=1.3, DT=None, **kwrd):
  tEf = (t-tIni)
  if (tEf<0) or (dtOff is None):
    return ampOn
  if DT is not None:
    tEf = tEf % DT
  if tEf>=0. and tEf<=dtOff:
    return 0.
  else:
    return ampOn


def eventoExtremo(t, Y):
  v, z = Y
  return v
